version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: conductor-db
    networks:
      default:
        aliases:
          - postgresdb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: conductor
      POSTGRES_PASSWORD: conductor
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conductor -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  conductor-server:
    image: conductoross/conductor:latest
    container_name: conductor-server
    ports:
      - "8080:8080" # API
      - "5000:5000" # UI
    environment:
      - CONFIG_PROP=config-postgres.properties
    depends_on:
      postgres:
        condition: service_healthy
