// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAALkdl1KPS8RYMiWjiCKwO4IyN0rRS3kY',
    appId: '1:572182442562:web:3104c9a65448d6c562b3db',
    messagingSenderId: '572182442562',
    projectId: 'mentor-me-ai',
    authDomain: 'mentor-me-ai.firebaseapp.com',
    storageBucket: 'mentor-me-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwDuqIuxskqxwE8fidyAkb4TBe8nRBTzg',
    appId: '1:572182442562:ios:1623bd9609fc299162b3db',
    messagingSenderId: '572182442562',
    projectId: 'mentor-me-ai',
    storageBucket: 'mentor-me-ai.firebasestorage.app',
    iosBundleId: 'com.calimbaios.calimbaios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwDuqIuxskqxwE8fidyAkb4TBe8nRBTzg',
    appId: '1:572182442562:ios:732b575d313c58df62b3db',
    messagingSenderId: '572182442562',
    projectId: 'mentor-me-ai',
    storageBucket: 'mentor-me-ai.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp.fix1',
  );
}
